### ISSUE TITLE
CPU Load

### ISSUE THREAD

**Issue by DirtyDanChicago** [DirtyDanChicago/ages-fpn-demo#7]
This scene, Graybox1, has taken up 100% of my CPU load and I can't work anymore as it keeps crashing Unity. No other scene is like this.

**Comment by dantogno** [comment]
@DirtyDanChicago What branch should I test on?

**Comment by DirtyDanChicago** [comment]
LevelDesign2

**Comment by dantogno** [comment]
I think it could be baking the lighting that is causing your CPU problems. Try going to **Window > Rendering >Lighting Settings** and uncheck **Baked Global Illumination** (under the **Mixed Lighting** heading).
