### ISSUE TITLE
Terrain Changing Cloned Terrain

### ISSUE THREAD

**Issue by DirtyDanChicago** [DirtyDanChicago/ages-fpn-demo#8]
The terrains of Graybox1 and Graybox2 are changing each other even though I have duplicated them, gave them new data, and cloned them every which way. The branch is Level-Design-2. Not sure what I'm doing wrong.

**Comment by dantogno** [comment]
https://forum.unity.com/threads/copying-terrain-data.78050/#post-3583077 this worked for me!
